services:
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  cache:
    image: redis
    container_name: cache
    restart: always
    volumes:
      - ./data/cache:/data

  nginx:
    build: ./config/nginx
    command: [ "nginx", "-g", "daemon off;" ]
    container_name: nginx
    restart: always
    links:
      - web
    volumes_from:
      - web
    ports:
      - "80:80"
      - "443:443"

  daphne:
    build: ./educa
    container_name: daphne
    working_dir: /code
    command: [ "./wait-for-it.sh", "db:5432", "--",
               "daphne", "-u", "/code/daphne.sock",
               "educa.asgi:application" ]
    restart: always
    volumes:
      - ./educa:/code
    environment:
      - DJANGO_SETTINGS_MODULE=educa.settings.prod
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - cache

  web:
    build: ./educa
    container_name: web
    command: [ "./wait-for-it.sh", "db:5432", "--",
               "uwsgi", "--ini", "/opt/conf/uwsgi/uwsgi.ini" ]
    restart: always
    volumes:
      - ./config:/opt/conf
      - ./educa:/code
    environment:
      - DJANGO_SETTINGS_MODULE=educa.settings.prod
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - cache